name: CI/CD Pipeline - Docker & AWS

# Se activa cuando haces un push a la rama 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: CI (Construir y Subir Imagen)
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el código
        uses: actions/checkout@v3

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Subir imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # IMPORTANTE: Cambia 'tu-usuario/tu-repo' por tu usuario real de Docker Hub
          tags: stoicpath/backend_helloworld:latest

  # TRABAJO 2: CD (Desplegar en AWS)
  deploy-to-aws:
    needs: build-and-push # Espera a que termine el paso anterior
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 # Cambia si usas otra región

      - name: Refrescar Auto Scaling Group
        # Este comando mata las instancias viejas y crea nuevas con la imagen 'latest'
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name examen-asg \
            --preferences '{"MinHealthyPercentage": 50}'